server:
  port: 8080

spring:
  application:
    name: web
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: web-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

api:
  basic-uri:
    storage: http://localhost:8081/