server:
  port: 8765

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#
#  cloud:
#    gateway:
#      routes:
#        - id: web
#          uri: http://localhost:8080
#          predicates:
#            - Path=/web-client/**
#        - id: storage
#          uri: http://localhost:8081
#          predicates:
#            - Path=/storage-user/**